"""initial schema + volunteer welcome token

Revision ID: c1efeb76ffc8
Revises: 
Create Date: 2026-05-17 19:13:05.716322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1efeb76ffc8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admins_reset_token'), ['reset_token'], unique=True)

    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('copyright_text', sa.String(length=500), nullable=True),
    sa.Column('provider_impressum_html', sa.Text(), nullable=True),
    sa.Column('landing_impressum_html', sa.Text(), nullable=True),
    sa.Column('log_retention_months', sa.Integer(), nullable=False),
    sa.Column('smb_enabled', sa.Boolean(), nullable=False),
    sa.Column('smb_server', sa.String(length=200), nullable=True),
    sa.Column('smb_share', sa.String(length=200), nullable=True),
    sa.Column('smb_path', sa.String(length=500), nullable=True),
    sa.Column('smb_username', sa.String(length=200), nullable=True),
    sa.Column('smb_password', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_slug'), ['slug'], unique=True)

    op.create_table('mail_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_server', sa.String(length=200), nullable=False),
    sa.Column('mail_port', sa.Integer(), nullable=False),
    sa.Column('mail_use_tls', sa.Boolean(), nullable=False),
    sa.Column('mail_username', sa.String(length=200), nullable=False),
    sa.Column('mail_password', sa.String(length=500), nullable=False),
    sa.Column('mail_default_sender', sa.String(length=200), nullable=False),
    sa.Column('mail_sender_name', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_instance_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizers_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizers_reset_token'), ['reset_token'], unique=True)

    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('volunteer_name', sa.String(length=100), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_volunteer_id'), ['volunteer_id'], unique=False)

    op.create_table('event_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'date', name='uq_event_date_instance')
    )
    with op.batch_alter_table('event_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_dates_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_dates_instance_id'), ['instance_id'], unique=False)

    op.create_table('organizer_instances',
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organizer_id', 'instance_id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=200), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.Column('mail_sender_name', sa.String(length=200), nullable=False),
    sa.Column('shifts_enabled', sa.Boolean(), nullable=False),
    sa.Column('food_donations_enabled', sa.Boolean(), nullable=False),
    sa.Column('site_locked', sa.Boolean(), nullable=False),
    sa.Column('lock_message', sa.Text(), nullable=True),
    sa.Column('log_retention_months', sa.Integer(), nullable=False),
    sa.Column('instance_impressum_html', sa.Text(), nullable=True),
    sa.Column('privacy_policy_html', sa.Text(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_settings_instance_id'), ['instance_id'], unique=True)

    op.create_table('stands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stands_instance_id'), ['instance_id'], unique=False)

    op.create_table('volunteers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('welcome_token', sa.String(length=64), nullable=True),
    sa.Column('welcome_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'email', name='uq_volunteer_email_instance')
    )
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteers_instance_id'), ['instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteers_reset_token'), ['reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_volunteers_welcome_token'), ['welcome_token'], unique=False)

    op.create_table('food_donation_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('event_date_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('delivery_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_donation_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_donation_types_event_date_id'), ['event_date_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_donation_types_instance_id'), ['instance_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stand_id', sa.Integer(), nullable=False),
    sa.Column('event_date_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('max_volunteers', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_date_id'], ['event_dates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stand_id'], ['stands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stand_id', 'event_date_id', 'start_time', 'end_time', name='uq_shift_slot')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_event_date_id'), ['event_date_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_stand_id'), ['stand_id'], unique=False)

    op.create_table('food_donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('food_type_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('needs_refrigeration', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['food_type_id'], ['food_donation_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_donations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_donations_food_type_id'), ['food_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_donations_volunteer_id'), ['volunteer_id'], unique=False)

    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volunteer_id', 'shift_id', name='uq_volunteer_shift')
    )
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registrations_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_volunteer_id'), ['volunteer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_registrations_shift_id'))

    op.drop_table('registrations')
    with op.batch_alter_table('food_donations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_donations_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_food_donations_food_type_id'))

    op.drop_table('food_donations')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_stand_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_event_date_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('food_donation_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_donation_types_instance_id'))
        batch_op.drop_index(batch_op.f('ix_food_donation_types_event_date_id'))

    op.drop_table('food_donation_types')
    with op.batch_alter_table('volunteers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteers_welcome_token'))
        batch_op.drop_index(batch_op.f('ix_volunteers_reset_token'))
        batch_op.drop_index(batch_op.f('ix_volunteers_instance_id'))
        batch_op.drop_index(batch_op.f('ix_volunteers_email'))

    op.drop_table('volunteers')
    with op.batch_alter_table('stands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stands_instance_id'))

    op.drop_table('stands')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_settings_instance_id'))

    op.drop_table('site_settings')
    op.drop_table('organizer_instances')
    with op.batch_alter_table('event_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_dates_instance_id'))
        batch_op.drop_index(batch_op.f('ix_event_dates_date'))

    op.drop_table('event_dates')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_volunteer_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_instance_id'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_event_type'))

    op.drop_table('activity_logs')
    with op.batch_alter_table('organizers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizers_reset_token'))
        batch_op.drop_index(batch_op.f('ix_organizers_email'))

    op.drop_table('organizers')
    op.drop_table('mail_settings')
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_slug'))

    op.drop_table('instances')
    op.drop_table('global_settings')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_reset_token'))
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
